import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    todoContainer: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    navContainer: {
        flex: 0,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    navHeader: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 5,
        textAlign: 'center'
    },
    buttonWrapper: {
        marginTop: 10,
        flexDirection: 'row',
        width: '90%',
        justifyContent: 'center',
    },
    button: {
        marginRight: 10,
        marginLeft: 10,
        paddingLeft: 8,
        paddingRight: 8,
        width: 'auto',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0077CC',
        borderRadius: 12,
    },
    buttonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    formWrapper: {
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    formHeader: {
        fontSize: 30,
        marginBottom: 5,
    },
    formText: {
        fontSize: 16,
        marginBottom: 10,
    },
    instructions: {
        fontSize: 12,
        fontStyle: 'italic',
        marginBottom: 10,
    },
    instructionsWrapper: {
        marginTop: 5,
        width: 'auto',
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    instructionsWrapperHide: {
        display: 'none'
    },
    shortInput: {
        paddingLeft: 8,
        width: '100%',
        height: 40,
        justifyContent: 'center',
        textAlign: 'left',
        alignItems: 'center',
        borderColor: '#0077CC',
        borderWidth: 2,
        borderRadius: 12,
        marginTop: 10,
        marginBottom: 10,
    },
    contentList: {
        height: '100%',
    },
    textFont: {
        fontSize: 28
    },
    inputBox: {
        width: 300,
        height: 40,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        marginTop: 40,
    },
    incomplete: {
        marginTop: 20,
        fontSize: 30,
        fontWeight: 'normal',
        fontStyle: 'normal',
        lineHeight: 40,

    },
    completed: {
        marginTop: 20,
        fontSize: 30,
        fontWeight: '900',
        textDecorationLine: 'line-through',
        fontStyle: 'italic',
        lineHeight: 40,
    },
    wrapScrollView: {
        flex: 1,
    },
    itemsAddWrapper: {
        flexDirection: 'row',
        width: 'auto',
        justifyContent: 'center',
        alignItems: 'center',
    },
    addButton: {
        paddingLeft: 8,
        paddingRight: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#0077CC',
        borderRadius: 12,
        width: '15%',
        height: 40,
    },
    addInput: {
        paddingLeft: 8,
        width: '80%',
        height: 40,
        justifyContent: 'center',
        textAlign: 'left',
        alignItems: 'center',
        borderColor: '#0077CC',
        borderWidth: 2,
        borderRadius: 12,
        marginTop: 10,
        marginBottom: 10,
        marginRight: 10,
    },
    helpInteractiveText: {
        fontSize: 14,
        fontWeight: 'bold',
        borderColor: '#0077CC',
        borderWidth: 2,
        borderRadius: 12,
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: 10,
        paddingBottom: 10,
        backgroundColor: '#0077CC',
        color: 'white',
    },
    helpInteractiveTextSmall: {
        fontSize: 14,
        fontWeight: 'bold',
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: 10,
        paddingBottom: 10,
        color: '#0077CC',
    },
});